# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f7e01e87a12e6630f21cceebe70f2e944bf0615e34e551aa33f02903d1f9255b7d932bd3a8e3e1ff7187faff86a9d41ef896239a30daaee73ebc21a2d771b34

test:
  secret_key_base: 64cd15ce2e3dcd8b4d0cb4fcfa2c87d552e3e392e72d5dfeebeca6b647602ea5e346454094b3bc96dabb25e169dbcba4affb478162a1e955b439d5777a42470c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
